import os
# os.system('pip install --upgrade torch')
# os.system('pip install --upgrade torchvision')
# os.system('pip install torch==1.10.0+cu111 torchvision==0.11.0+cu111 torchaudio==0.10.0 torchtext==0.11.0 -f https://download.pytorch.org/whl/torch_stable.html')
# os.system('pip install torch==0.14.0+cu11 torchvision==0.13.1+cu113 torchaudio==0.12.1 --extra-index-url https://download.pytorch.org/whl/cu113')

# os.system('pip install torch==1.13.0+cu116')
# os.system('pip install torchvision==0.14.0+cu116')
# os.system('pip install torchtext==0.14.0')
# os.system('pip install torchaudio==0.13.0')

# os.system('pip install --upgrade --force-reinstall --no-deps kaggle')
os.system('pip install einops==0.3.0')
os.system('pip install qudida')
os.system('pip install logging')
os.system('pip install torchmetrics')
os.system('pip install ttach')
os.system('pip install tabulate')
os.system('pip install ml-collections==0.1.0')
os.system('pip install einops')
# os.system('pip install synapseclient')
os.system('pip install scipy==1.5.4')
os.system('pip install albumentations==1.2.1')
os.system('pip install timm')
os.system('pip install numpy')
os.system('pip install h5py')
os.system('pip install wget')
os.system('pip install tensorboardX==2.4')
os.system('pip install SimpleITK==2.1.1')
os.system('pip install MedPy==0.4.0')
os.system('pip install paddlepaddle')
os.system('pip install opencv-python')
os.system('pip install paddleseg')

# os.system('pip install --upgrade --force-reinstall --no-deps albumentations')

os.system('conda install pytorch torchvision torchaudio pytorch-cuda=11.7 -c pytorch -c nvidia')

