import os
# os.system('pip install --upgrade torch')
# os.system('pip install --upgrade torchvision')
# os.system('pip install torch==1.10.0')
# os.system('pip install torch==1.10.0+cu111')
os.system('pip install torch==1.10.0+cu111 torchvision==0.11.0+cu111 torchaudio==0.10.0 torchtext==0.11.0 -f https://download.pytorch.org/whl/torch_stable.html')
# os.system('pip install torchvision==0.11.1')
os.system('pip install --upgrade --force-reinstall --no-deps kaggle')
os.system('pip install einops==0.3.0')
os.system('pip install qudida')
os.system('pip install logging')
os.system('pip install tabulate')
os.system('pip install ml-collections==0.1.0')
# os.system('pip install synapseclient')
os.system('pip install scipy==1.5.4')
os.system('pip install numpy')
os.system('pip install h5py')
os.system('pip install wget')
os.system('pip install tensorboardX==2.4')
os.system('pip install SimpleITK==2.1.1')
os.system('pip install MedPy==0.4.0')
# os.system('pip install --upgrade --force-reinstall --no-deps albumentations')


